### ISSUE TITLE
Deployment of React Application

### ISSUE THREAD

**Issue by bekirtatar** [bounswe/2021SpringGroup11#154]
The development branch of our react application will be deployed to AWS servers using AWS S3 service and GitHub actions.

DEADLINE: 11/13/2021

**Comment by meltemarsl** [comment]
The branch has deployed to AWS S3, you can check it now

**Comment by emindeniz99** [comment]
Thanks for your works. It works 🚀 . I can not access /login page directly, because s3 serves files. But there is not any file named "login.html" etc.
![image](https://user-images.githubusercontent.com/44745432/141647647-b5b23d91-c29d-4a77-808a-ba5c4d9efbba.png)


There are hacks for client side routing on aws s3. You can check first option at this link https://stackoverflow.com/questions/51218979/react-router-doesnt-work-in-aws-s3-bucket/52346186#52346186 
![image](https://user-images.githubusercontent.com/44745432/141647605-61d58e29-51a2-4ba7-b3db-7a55abd44b5d.png)

**Comment by meltemarsl** [comment]
The error has been fixed, you can check it and then close the issue

**Comment by emindeniz99** [comment]
Working properly 🚀
