### ISSUE TITLE
Path page implementation and fixes

### ISSUE THREAD

**Issue by bekirtatar** [bounswe/2021SpringGroup11#422]
There are some features that need to be added to the path page.

- Create Path will be modified
- Resources will be added

Deadline: 12.30 1/4/2022

**Comment by meltemarsl** [comment]
A resource section was added to the path page including the resources added by users. The resources should be related to some tasks or milestones so that they can be opened when clicked to a task or milestone.

The part looks like:

<img width="934" alt="451" src="https://user-images.githubusercontent.com/44238703/148588128-f46cfa20-e830-42be-81e0-a8bec2943fb5.png">
